### ISSUE TITLE
Property 'on' does not exist on type 'IJitsiMeetExternalApi'

### ISSUE THREAD

**Issue by federico-ntr** [jitsi/jitsi-meet-react-sdk#10]
`addEventListener` and `addEventListeners` are deprecated and the comment suggests to use `on` instead but it is not exported from `IJitsiMeetExternalApi`, which leads to error in title (ts2339).

**Comment by mihhu** [comment]
Could you please tell me when does this error show up? I can't seem to reproduce it. The `IJitsiMeetExternalApi` should inherit the `on` method from the `EventEmitter` class.

**Comment by federico-ntr** [comment]
The error used to show up on VSCode but it seems I'm not able to reproduce it anymore. I have just opened the project where it used to show up and now it works fine. Hovering on `on` even shows me the JSDocs. I didn't change anything so it's pretty weird, but I guess the issue can be closed. Sorry for the useless issue.
