### ISSUE TITLE
Object returned by getIFrameRef is not reactive

### ISSUE THREAD

**Issue by federico-ntr** [jitsi/jitsi-meet-react-sdk#16]
I have a boolean variable which should control some of the styles of Jitsi. 

```javascript
<JitsiMeeting
  domain={content.domain}
  roomName={content.roomName}
  onApiReady={handleApiReady}
  getIFrameRef={(iframeRef) => {
    iframeRef.style.height = "calc(100% - 35px)";
    iframeRef.style.pointerEvents = minimized ? "none" : "unset"
  }}
/>
```

I expect the style attribute of the iframe to change when the value of `minimized` changes but it doesn't.

![not minimized](https://user-images.githubusercontent.com/35468654/169323224-d1b8a9bf-09f0-4392-ba0d-1a2e0ec837dd.png)

![minimized](https://user-images.githubusercontent.com/35468654/169323490-dfbb79f9-b1d0-4846-a494-5d10a414eb22.png)

It may be that it's completely impossible to do this thing and I'm missing some fundamental concept of how this works.

**Comment by saghul** [comment]
I'd say you want to get the ref and update the style when the minimized variable changes. The `getIFrameRef` will only be called once, when the API object is created.

**Comment by mihhu** [comment]
Confirming what @saghul said. Please save the `getIFrameRef` argument into a local ref that you can adjust whenever you need. [Here](https://codesandbox.io/s/jitsi-react-sdk-style-demo-bzjmpm?file=/src/App.js)'s a tiny demo of how it should work.

**Comment by federico-ntr** [comment]
> I'd say you want to get the ref and update the style when the minimized variable changes. The `getIFrameRef` will only be called once, when the API object is created.

Yes, I should've known, it was actually pretty obvious.



> Confirming what @saghul said. Please save the `getIFrameRef` argument into a local ref that you can adjust whenever you need. [Here](https://codesandbox.io/s/jitsi-react-sdk-style-demo-bzjmpm?file=/src/App.js)'s a tiny demo of how it should work.

Really thanks for even providing an example!
