### ISSUE TITLE
"@jitsi/react-sdk doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix."

### ISSUE THREAD

**Issue by andersaamodt** [jitsi/jitsi-meet-react-sdk#17]
Trying to compile with Vite + TypeScript and getting this error

**Comment by andersaamodt** [comment]
I manually added `"type": "module"`, to the package.json file in node_modules/@jitsi/react-sdk and it made this error go away

**Comment by mihhu** [comment]
Sorry for the late reply, are you using a vite template?

**Comment by andersaamodt** [comment]
I used the built-in typescript-react template, yes

**Comment by andersaamodt** [comment]
I think it's gone away for me, too. Checking the package.json, the module line is gone, so I guess it got updated and overwritten and the error hasn't come back. I'll let you know if it reappears with more detail.

**Comment by decanTyme** [comment]
Can we reopen this? I'm getting the error:

```txt
[vite] Error when evaluating SSR module virtual:remix/server-build: failed to import "@jitsi/react-sdk"
|- Error: Directory import 'D:\Projects\Web\motli-session-compiler-alpha\node_modules\@jitsi\react-sdk\lib\components' is not supported resolving ES modules imported from D:\Projects\Web\motli-session-compiler-alpha\node_modules\@jitsi\react-sdk\lib\index.js
    at finalizeResolution (node:internal/modules/esm/resolve:263:11)
    at moduleResolve (node:internal/modules/esm/resolve:860:10)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:654:12)
    at ModuleLoader.#cachedDefaultResolve (node:internal/modules/esm/loader:603:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:586:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:242:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:135:49)
```

My setup is Remix (v2.15.1) + Vite (v6.0.3, also tried with latest v5), and I'm trying to make it work by:

```tsx
import { JitsiMeeting } from "@jitsi/react-sdk"

...

// copied from jitsi react sdk docs
<JitsiMeeting
  roomName="PleaseUseAGoodRoomName"
  configOverwrite={{
    startWithAudioMuted: true,
    disableModeratorIndicator: true,
    startScreenSharing: true,
    enableEmailInStats: false,
  }}
  interfaceConfigOverwrite={{
    DISABLE_JOIN_LEAVE_NOTIFICATIONS: true,
  }}
  userInfo={{ email: "EMAIL", displayName: "YOUR_USERNAME" }}
  onApiReady={(externalApi) => {
    // here you can attach custom event listeners to the Jitsi Meet External API
    // you can also store it locally to execute commands
  }}
  getIFrameRef={(iframeRef) => {
    iframeRef.style.height = "400px"
  }}
/>
```

Odd thing is, I tried to build and import it locally myself and it seems to work. My project has the `"type": "module"` in the package.json tho if that matters.

**Comment by norbertrost** [comment]
We are experiencing the same problem with the following package.json constellation, using node 20 and next14.
We did not found a workaround yet.

So we are interested in re-opening this issue and find a valid solution.

Interesting point may be:
If a user just walks from page to page and comes to the page with the react-sdk usage, all is fine. But if we reload this page, the error occurs like described by decanTyme.

  "dependencies": {
    "@appigram/react-rangeslider": "^2.2.15",
    "@jitsi/react-sdk": "^1.4.4",
    "@popperjs/core": "^2.11.8",
    "@redux-devtools/extension": "^3.2.2",
    "@reduxjs/toolkit": "1.9.7",
    "@sentry/nextjs": "^6.19.4",
    "@types/lodash.clonedeep": "^4.5.7",
    "@types/luxon": "^3.3.4",
    "@types/mime-types": "^2.1.1",
    "@types/scss-parser": "^1.0.1",
    "axios": "^1.6.8",
    "bootstrap": "^5.3.3",
    "date-fns": "^2.28.0",
    "formik": "^2.2.9",
    "globals": "^15.3.0",
    "html-to-react": "^1.6.0",
    "intl": "^1.2.5",
    "intl-pluralrules": "^1.3.1",
    "jquery": "^3.6.0",
    "js-cookie": "^3.0.1",
    "json-object-merge": "^1.2.0",
    "json-stable-stringify": "^1.1.1",
    "jwt-decode": "^3.1.2",
    "leaflet": "^1.9.4",
    "leaflet-draw": "^1.0.4",
    "leaflet-draw-locales": "^1.2.3",
    "lodash.clonedeep": "^4.5.0",
    "lodash.get": "^4.4.2",
    "lodash.has": "^4.5.2",
    "luxon": "^3.4.3",
    "mime-types": "^2.1.35",
    "next": "^14.1.4",
    "next-cookies": "^2.0.3",
    "next-redux-wrapper": "^7.0.5",
    "next-translate": "^2.6.2",
    "next-translate-plugin": "^2.6.2",
    "nextjs-progressbar": "^0.0.14",
    "prop-types": "^15.8.1",
    "qs": "^6.10.3",
    "rc-slider": "^9.7.5",
    "react": "18.3.1",
    "react-autosuggest": "^10.1.0",
    "react-csv": "^2.2.2",
    "react-datepicker": "^4.7.0",
    "react-dom": "^18.2.0",
    "react-idle-timer": "^4.6.4",
    "react-infinite-scroll-component": "^6.1.0",
    "react-inlinesvg": "^4.1.3",
    "react-jitsi": "^1.0.4",
    "react-leaflet": "^4.2.1",
    "react-leaflet-draw": "^0.20.4",
    "react-quill": "^2.0.0-beta.2",
    "react-redux": "^7.2.8",
    "react-select": "^5.2.2",
    "react-sortablejs": "^6.1.4",
    "react-spring-carousel-js": "^1.9.32",
    "react-timeout": "^2.0.1",
    "react-toastify": "^10.0.5",
    "reactstrap": "^9.2.2",
    "redux": "^5.0.1",
    "redux-saga": "^1.3.0",
    "redux-saga-callback": "^1.1.0",
    "rss-parser": "^3.13.0",
    "scss-parser": "^1.0.6",
    "sharp": "^0.32.1",
    "sortablejs": "^1.15.0",
    "string-strip-html": "8.5.0",
    "tsconfig-paths-webpack-plugin": "^3.5.2",
    "tslib": "^2.5.0",
    "uuid": "^9.0.0"
  },
  "devDependencies": {
    "@digitak/esrun": "^3.2.25",
    "@eslint/js": "^8.57.0",
    "@next/bundle-analyzer": "^12.1.4",
    "@next/eslint-plugin-next": "^14.2.4",
    "@testing-library/jest-dom": "^6.4.6",
    "@testing-library/react": "^14.2.1",
    "@testing-library/user-event": "^14.6.1",
    "@types/eslint__js": "^8.42.3",
    "@types/jest": "^29.5.12",
    "@types/js-cookie": "^3.0.1",
    "@types/json-stable-stringify": "^1.0.36",
    "@types/leaflet": "^1.9.8",
    "@types/lodash": "^4.14.181",
    "@types/node": "^20.11.30",
    "@types/popper.js": "^1.11.0",
    "@types/qs": "^6.9.7",
    "@types/react": "^18.0.1",
    "@types/react-autosuggest": "^10.1.11",
    "@types/react-csv": "^1.1.10",
    "@types/react-datepicker": "^4.3.4",
    "@types/react-leaflet": "^3.0.0",
    "@types/react-redux": "^7.1.23",
    "@types/react-test-renderer": "^18.0.7",
    "@types/react-timeout": "^1.1.3",
    "@types/rss": "^0.0.31",
    "@types/sortablejs": "^1.10.7",
    "@types/uuid": "^8.3.4",
    "@typescript-eslint/eslint-plugin": "^7.13.0",
    "@typescript-eslint/parser": "^7.13.0",
    "axios-mock-adapter": "^1.22.0",
    "cross-env": "^7.0.3",
    "deepl-node": "^1.10.2",
    "dpdm": "^3.14.0",
    "eslint": "^8.57.0",
    "eslint-config-next": "^14.2.4",
    "eslint-import-resolver-typescript": "^3.6.1",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-jsdoc": "^48.2.12",
    "eslint-plugin-prefer-arrow": "^1.2.3",
    "eslint-plugin-react": "^7.34.2",
    "eslint-plugin-react-hooks": "^4.6.2",
    "jest": "^29.7.0",
    "jest-environment-jsdom": "^29.7.0",
    "madge": "^8.0.0",
    "react-test-renderer": "^18.2.0",
    "redux-saga-test-plan": "^4.0.4",
    "rss": "^1.2.2",
    "sass": "^1.49.11",
    "ts-jest": "^29.1.2",
    "typescript": "^5.4.5",
    "typescript-eslint": "^7.13.0"
  },


Additionally:
When we run tests jest also has a problem with the usage of the SDK:

----
Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

/webclient/develop/node_modules/@jitsi/react-sdk/lib/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export * from './components';
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import { JitsiMeeting as JitsiMeetingSDK } from '@jitsi/react-sdk'
