### ISSUE TITLE
Accessing redux store features/base/tracks

### ISSUE THREAD

**Issue by santo4ul** [jitsi/jitsi-meet-react-sdk#18]
Hi,

I'm trying to access the remote audio stream (incoming) of a conferene. I'm doing this to record the incoming audio stream to a wav file. 

Based on information given [here](https://community.jitsi.org/t/recording-audio-using-wav-format/115952/8?u=santhosh_muralidhara),  the incoming (remote) audio stream is available at the redux store `features/base/tracks`. 

Is it possible to access the redux store `features/base/tracks` from jitsi-meet-react-sdk? Any hint on achieving this would be really great. 

Thank you.

**Comment by saghul** [comment]
Hi there!

Interesting use case.

This SDK uses our external API internally, which loads the meeting in an iframe, and we send commands and get events using the `postMessage` API. It's not technically possible to send a MediaStreamTrack over `postMessage` so I'm afraid what you ask is not possible.
