### ISSUE TITLE
ClockSync net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by Tech-Dex** [jitsi/jitsi-meet-react-sdk#22]
Hello.

I am trying to use the very basics and I am facing a weird issue. In short terms: sometimes jitsi react sdk works without any problem and sometimes it doesn't.

I think the below image provides most of the details you'll need:
![image](https://user-images.githubusercontent.com/44111988/186887777-6489693e-9a11-47b8-90cd-a6cf0f328a16.png)

Code:
```js
const configOverwrite = {
    startWithAudioMuted: true,
    hiddenPremeetingButtons: ['microphone'],
  };

const userInfo = {
    displayName: auth.user.username,
    email: auth.user.email,
  };

const handleExitMeeting = () => {
    navigator('/');
  };

<JitsiMeeting
              roomName={searchParams.get('roomName')}
              getIFrameRef={(node) => (node.style.height = conferenceHeight)}
              onReadyToClose={() => handleExitMeeting()}
              configOverwrite={configOverwrite}
              userInfo={userInfo}
              spinner={() => {
                return <Spinner animation="border" />;
              }}
            />

```

**Comment by saghul** [comment]
That's due to the default callstats integration. Is it set for your domain? You can disable it by overriding `callStatsID` and `callStatsSecret` with the empty string.

**Comment by Tech-Dex** [comment]
Hello @saghul.
Yes, it is set on a domain. My initial thought was that is a issue related to time zones difference.
Are there any issues in the future with empty strings for callStats*?
I will try this and I am sorry for bothering you, thank you a lot.

**Comment by saghul** [comment]
No issues related to that, other than that you'll be disabling callstats.

**Comment by Tech-Dex** [comment]
Hello @saghul .

I am sorry to reopen this but I have one more question around amplitude. Right now it seems like the above behaviour is produced by a CORS error and sometimes the call will work and sometimes will fail. Is there any way to avoid this issue? I don't know if it possible to add my domain in amplitude server in order to avoid this CORS issue.
I found that in the config.js there is a key "amplitudeAPPKey" and I tried to set it to an empty string but this will result in a constant error.

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/44111988/187621087-055a3e50-fdbe-4af0-9092-2dd0437e0d78.png">

**Comment by saghul** [comment]
If you don't set an amplitude key amplitude wont be used at all. How are you setting it?

**Comment by Tech-Dex** [comment]
Right now I am not setting it:

```js
  const configOverwrite = {
    startWithAudioMuted: true,
    hiddenPremeetingButtons: ['microphone'],
    callStatsID: '',
    callStatsSecret: '',
  };
  ```

**Comment by Tech-Dex** [comment]
@saghul 
Sorry to bother you again. Any idea around the above issue? I still can't get over it.

**Comment by saghul** [comment]
Add the following to your overrides:

```
analytics: {
    amplitudeAPPKey: ''
}
```
