### ISSUE TITLE
getRoomsInfo() does not exist as a function?

### ISSUE THREAD

**Issue by Papillon6814** [jitsi/jitsi-meet-react-sdk#31]
Hello.
I'm wondering [getRoomsInfo() function](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe-functions/#getroomsinfo) does not exist in this repository yet 🤔 
If there's not, may I create a pull request for that?

Thank you for your attention.

**Comment by mihhu** [comment]
hey, it's already implemented within the JitsiMeetExternalApi, if you want to use it you can simply call it on your instance:
`apiRef.current.getRoomsInfo().then(rooms => console.log(rooms));`

**Comment by Papillon6814** [comment]
Ohh okay! Thank you for the info!
