### ISSUE TITLE
Called JitsiMeetElectron.obtainDesktopStreams but it is not defined

### ISSUE THREAD

**Issue by JMSevilla** [jitsi/jitsi-meet-react-sdk#35]
Hi i'm trying to use @jitsi/react-sdk on my electron

whenever I try to share my screen it doesn't work and there is no sharing option showing up

**Comment by damencho** [comment]
In your electron app you need to use 
https://github.com/jitsi/jitsi-meet-electron-sdk#screen-sharing

**Comment by JMSevilla** [comment]
Can you show me how to use it ?

**Comment by JMSevilla** [comment]
Can I drop here my existing code because I'm using also @jitsi/react-sdk it is working on web but when in electron it is not.

**Comment by damencho** [comment]
You can check the code in https://github.com/jitsi/jitsi-meet-electron how it uses it.

**Comment by JMSevilla** [comment]
Because I had a react typescript project inside my electron root directory project. so I'm using JaasMeeting upon trying to share screen event though I have setupScreenSharingRender and setupScreenSharingMain it is not working
