### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by jgarplind** [jitsi/jitsi-meet-react-sdk#36]
As per https://community.jitsi.org/t/default-language/114671/20 the highest prioritized language is that set as a query parameter.

I cannot find any way to do this using this library, but a wild guess would be that it should be implemented the same way as the `release` query parameter [here](https://github.com/jitsi/jitsi-meet-react-sdk/blob/main/src/init.ts#L14)?

**Comment by mihhu** [comment]
You can pass the [defaultLanguage](https://github.com/jitsi/jitsi-meet/blob/0becc890d8c4578d52ab6836da11dae340313ddd/react/features/base/util/uri.ts#L544) to the configOverwrite prop, I think it was added after that community thread.

**Comment by mihhu** [comment]
> You can pass the [defaultLanguage](https://github.com/jitsi/jitsi-meet/blob/0becc890d8c4578d52ab6836da11dae340313ddd/react/features/base/util/uri.ts#L544) to the configOverwrite prop

Made some tests and noticed it can't be overridden, can you please confirm? Based on the code I've referenced above I'd say the query param and config are equivalent.

**Comment by jgarplind** [comment]
🗒️ As per everything I can find documented, you are correct that `defaultLanguage` cannot be overridden, at least based on a default installation with [this whitelist](https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/config/configWhitelist.ts).

Also [this comment stating](https://github.com/jitsi/jitsi-meet/blob/master/config.js#L634)

> // Default language for the user interface. Cannot be overwritten.

❗ ... still, at least on my localhost, I just tried (maybe for the first time?) setting `configOverwrite={{defaultLanguage: "en"}}`, and it just worked.

----
I'm a bit confused, but temporarily relieved. Maybe this ought to be documented somehow?

**Comment by mihhu** [comment]
After further investigation I think the fact that it works might be a bug that needs to be fixed in jitsi-meet, as the current implementation takes the defaultLanguage from the url directly, without taking into account the whitelist filtering. I'm going to implement lang as a prop for JitsiMeeting, as you've suggested, until we clear that up.

**Comment by mihhu** [comment]
Released [v1.4.0](https://github.com/jitsi/jitsi-meet-react-sdk/releases/tag/v1.4.0) that supports `lang`. We'll mark defaultLanguage as deprecated, but keep it around for backwards compatibility. Thanks for pointing this out!

**Comment by jgarplind** [comment]
@mihhu I just got around to testing the new `lang` prop, and unfortunately I think it doesn't work?

Specifically, it seems that [browser language detection](https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/i18n/customNavigatorDetector.ts#L20) takes precedence over the `lang` prop (unlike the `defaultLang` prop!), so as long as the language detector finds something that matches a language known to the Jitsi server, the `lang` prop has 0 impact.

This behavior could be acceptable for a prop called `defaultLanguage`, but when I explicitly set `lang: xx`, I expect it to be honored over other more implicit ways of setting the language.

**Comment by jgarplind** [comment]
Closing since it is fixed and confirmed. Thanks a lot for the quick solution!
