### ISSUE TITLE
After ending call, the space occupied by the JaaSMeeting component becomes blank

### ISSUE THREAD

**Issue by anisharya16** [jitsi/jitsi-meet-react-sdk#41]
I am using JaaSMeeting component in my React application. I have it in right side of my app. When I end the meeting the space is empty and it does not look good. Is there a way to show something like "Meeting has ended" or relaunch the meeting.

Current Code:
 ```
<JaaSMeeting
          appId={"my-app-id"}
          roomName="DoctorRoomForPatients"
          configOverwrite={{
            disableThirdPartyRequests: true,
            disableLocalVideoFlip: true,
            backgroundAlpha: 0.5,
            startWithAudioMuted: true,
            startWithVideoMuted: true,
            enableNoAudioDetection: true,
            enableNoisyMicDetection: true,
            startAudioMuted: 10,
            startVideoMuted: 10,
          }}
          getIFrameRef={(iframeRef) => {
            iframeRef.style.height = "100vh";
          }}
        />

```
Adding Screenshots for the current behaviour.
![Screenshot from 2024-04-16 15-02-41](https://github.com/jitsi/jitsi-meet-react-sdk/assets/22936519/540bfd62-1679-4300-a8f6-b33993adec61)
After ending the call:
![Screenshot from 2024-04-16 15-02-54](https://github.com/jitsi/jitsi-meet-react-sdk/assets/22936519/1d304782-95a2-4568-8598-b4fbc97aa243)

Or is there any other way to mitigate this?

**Comment by mihhu** [comment]
Please try using [this callback](https://github.com/jitsi/jitsi-meet-react-sdk?tab=readme-ov-file#onreadytoclose) that gets executed when the conference ends and display anything you need instead.

**Comment by anisharya16** [comment]
> Please try using [this callback](https://github.com/jitsi/jitsi-meet-react-sdk?tab=readme-ov-file#onreadytoclose) that gets executed when the conference ends and display anything you need instead.

This worked. Thanks.
