### ISSUE TITLE
How to change the language file of Jitsi JAAS?

### ISSUE THREAD

**Issue by vnfcms** [jitsi/jitsi-meet-react-sdk#42]
I'm using your package and utilizing JAAS. When switching to Japanese language, there are many untranslated keys. How can I modify? Can I add keys or edit some of the existing Japanese sentences?

Thanks

**Comment by saghul** [comment]
Hey there! You have 2 ways:

1) Contribute to jitsi-meet so the untranslated labels are actually translated: https://github.com/jitsi/jitsi-meet/tree/master/lang#jitsi-meet-translation
2) Use dynamic branding in JaaS to override the translation keys you want: https://developer.8x8.com/jaas/docs/jaas-prefs-advanced-branding#branding-data-payload check the section for `labels`

**Comment by vnfcms** [comment]
Thank you for your support.
If I choose option 2, are these the steps to follow?
1. Log in to https://jaas.8x8.vc/.
2. Select Branding from the menu, then choose Advanced Settings.
3. Click on the "Add branding resources URL" button.
4. Enter the URL as the JSON data of the payload.

Additionally, is there a way I can directly set up from the source code without accessing the website for configuration? If so, could you please guide me?
Thank you!

**Comment by saghul** [comment]
In 4 you need to pass an actual URL which will respond with the JSON payload.



> Additionally, is there a way I can directly set up from the source code without accessing the website for configuration? If so, could you please guide me?
> Thank you!

This is not currently possible.

**Comment by vnfcms** [comment]
Thanks for your help!

**Comment by saghul** [comment]
Cheers! Feel free to close this when you're ready.

**Comment by vnfcms** [comment]
Hi @saghul,
I've utilized this payload from https://www.vongquanhvietnam.com/jitsi.php. They offer two settings: en and ja, both of which are in Japanese. However, it still appears in English. Is there and mistake from me?
![image](https://github.com/jitsi/jitsi-meet-react-sdk/assets/507414/5ac55aa6-9c51-4d90-af7c-8173a8e19b27)
